### ISSUE TITLE
Relationship support

### ISSUE THREAD

**Issue by jmauersberger** [JamaSoftware/RestClient#13]
Is there any example how to create or change relationships? I am not fully sure whether the current API support is sufficient?

**Comment by ibilal-jama** [comment]
You're absolutely correct. Creating and changing relationships is not currently supported by the client, but they are very much integral endpoints to have as part of this client. I'll be picking this story up and adding it to my active projects. I'll check back in with you when I get into the implementation to get feedback along the way.

**Comment by ibilal-jama** [comment]
@jmauersberger I've updated the branch [here](https://github.com/JamaSoftware/RestClient/tree/create-update-relationships) to now allow for updating and creating new Jama Relationships. Can you take a look and let me know how this works for you? Once you give me the go ahead, I'll merge this branch into master.

**Comment by jmauersberger** [comment]
@ibilal-jama ok, will do

**Comment by jmauersberger** [comment]
@ibilal-jama Works like a charm, I was able to create and fetch relationships. So I think we can merge this back to master and close this issue.

Ah, any hint how to delete a relationship?

**Comment by ibilal-jama** [comment]
We haven't added in support for deleting item or relationships yet. Is this something you think will be required to move forward with the proxy work? Or can it wait?

**Comment by jmauersberger** [comment]
Well, I think it would be required to fully support relationship synchronization. So would be great if we can approach this next.

**Comment by jmauersberger** [comment]
Iman, have you been working on deletion support yet?
Thanks Jan

**Comment by ibilal-jama** [comment]
Hi Jan, 
I have not started on adding relationship deletion support due to other customer engagements. I can add this support in by the end of the year. Will this timeframe work for you and your team?

**Comment by jmauersberger** [comment]
I need to check with the team - I think we meanwhile approached it ourselves and will provide a patch but not sure whether its for deletion of items or relationships or both. I will update you in this thread.

**Comment by jmauersberger** [comment]
Iman, I clarified that issue: we have implemented relationship deletion ourselves (contribution will follow within this year I think) but we are missing item deletion itself. Could you help us here?

Thanks Jan

**Comment by jmauersberger** [comment]
Iman, I have to correct myself: we have added support for deletion of objects and relationships via REST but only as a workaround in our code until that's supported by this Java wrapper. So the issue is till open for both, items and relationships and we don't have a contribution we can post, I'm sorry.

**Comment by rubenzimmermann** [comment]
Hi, I forgot to mention this ticket in pull request #18.
I provided a very minimal solution to add support for deleting items and relationships.

**Comment by ibilal-jama** [comment]
Hi Jan, 
I've added in support for the delete items and relationships. Please see examples of usage in Main.
