### ISSUE TITLE
Commit result inspection

### ISSUE THREAD

**Issue by jmauersberger** [JamaSoftware/RestClient#17]
Is it somehow (maybe already now?) possible to inspect the result of a commit and at least check whether the item was changed in some way or not?

**Comment by ibilal-jama** [comment]
If you are referring to a Github commit, under the <> code tab in the header, you should be able to navigate to a particular file and a "History" button should appear. Clicking on this will reveal all commits and the changes made in each commit.

**Comment by jmauersberger** [comment]
Ah, sorry Iman, that was misleading. I was refering to a Jama commit. After we have changed and comitted a set of objects to Jama we are showing a kind of reuslt page were we at least tell the number of creations, deletions and modifications. For the later, we somehow need to know whether we really changed somethign or not.

**Comment by ibilal-jama** [comment]
You can tell whether or not an item has been updated using the lastModifiedDate. If the date is same as the last commit date, it was most likely updated. If it's older, no updates occurred.
