### ISSUE TITLE
TestRuns update 

### ISSUE THREAD

**Issue by hussamcs** [JamaSoftware/RestClient#19]
Hello, 

Do the rest API support TestRuns updates? 
my usecase: having testrun in JAMA with some custom fields and I want to update the values of all or some of custome fields. 

Best Regards,
Ibrahim

**Comment by nmchale-jama** [comment]
Hello Ibrahim, 

Unfortunately, it is not possible to update custom fields on a TestRun.  This is a known limitation within the API.  

Best Regards,
Nick
