### ISSUE TITLE
Observing Jama server version

### ISSUE THREAD

**Issue by jmauersberger** [JamaSoftware/RestClient#20]
Hello guys,
is there by chance already a way to obtain the version of the Jama server after connection?

Thanks a lot
Jan

**Comment by nmchale-jama** [comment]
Hello Jan,
     Unfortunately there is not a way to obtain the Jama Server version through the REST Client.  The Jama Connect API currently does not expose this information through the REST API. Therefore it is not available in this REST Client.
     I think supplying the version number is a good idea and I will drop it in the feature requests box for consideration in a future API version.

Best Regards,
Nick McHale
Jama Software

**Comment by jmauersberger** [comment]
OK, thanks Nick
Jan
